from sqlalchemy import Column, Integer, String, DateTime, Boolean
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
from database import Base
import uuid

class Client(Base):
    __tablename__ = "tbClients"

    OID = Column(UNIQUEIDENTIFIER, primary_key=True, default=uuid.uuid4, index=True)
    systemKey_str = Column(String(20), nullable=False)
    customerCode_str = Column(String(14), nullable=True)
    customerID = Column(Integer, nullable=False)
    customerOID = Column(UNIQUEIDENTIFIER, nullable=True)
    lastName_str = Column(String(30), nullable=True)
    firstName_str = Column(String(30), nullable=True)
    nationalIdNumber_str = Column(String(20), nullable=True)
    registrationDate_dat = Column(DateTime, nullable=True)
    customerInternalNo_CIN = Column(String(30), nullable=True)
    registrationNo_str = Column(String(20), nullable=False)
    birthDate_dat = Column(DateTime, nullable=True)
    entryServicePoint = Column(String(40), nullable=True)
    otherName_str = Column(String(30), nullable=True)
    initials_str = Column(String(5), nullable=True)
    gender_str = Column(String(1), nullable=True)
    clientDescription_str = Column(String(150), nullable=True)
    maritalStatus_str = Column(String(30), nullable=True)
    classification_str = Column(String(50), nullable=True)
    phoneNumber_str = Column(String(20), nullable=True)
    email_str = Column(String(4000), nullable=True)
    addressPostal_str = Column(String(50), nullable=True)
    addressPostalCity_str = Column(String(30), nullable=True)
    addressResidential_str = Column(String(100), nullable=True)
    active_bol = Column(Boolean, nullable=False)
    inActiveReason_str = Column(String(40), nullable=True)
    addedDate_dat = Column(DateTime, nullable=True)
    addedUser_str = Column(String(150), nullable=True)
    lastUpdateDate_dat = Column(DateTime, nullable=True)
    lastUpdateBy_str = Column(String(150), nullable=True)
    cacheVisitDate_dat = Column(DateTime, nullable=True)
    deleted_bol = Column(Boolean, nullable=True)
    deletedBy_str = Column(String(150), nullable=True)
    deletetedReason_str = Column(String(250), nullable=True)
    clientPhoto_img = Column(String, nullable=True)
    flagPrintCol_bol = Column(Boolean, nullable=True)
    deletedDate_dat = Column(DateTime, nullable=True)
    cacheCustName_str = Column(String(70), nullable=True)
    seqINT = Column(Integer, nullable=False)
    entryServicePointOID = Column(UNIQUEIDENTIFIER, nullable=True)
    QRcode_str = Column(String, nullable=True)
    passportTravelNo_str = Column(String(15), nullable=True)
    locked_bol = Column(Boolean, nullable=True)
    lockedBy_str = Column(String(150), nullable=True)
    lockedDate_dat = Column(DateTime, nullable=True)
    lockedMachine_str = Column(String(250), nullable=True)
    nationality_str = Column(String(30), nullable=True)
    cacheVaccine_str = Column(String(30), nullable=True)
    cacheVacCard_bol = Column(Boolean, nullable=True)
    machine_str = Column(String(100), nullable=True)
    machineID = Column(String(20), nullable=True)
    notes_str = Column(String, nullable=True)
    extSysOID_ART = Column(UNIQUEIDENTIFIER, nullable=True)
    regionLocale_str = Column(String(150), nullable=True)
    religion_str = Column(String(100), nullable=True)
    ethnicity_str = Column(String(100), nullable=True)
    birthDate_calcYN = Column(Boolean, nullable=True)
    cache_ageBandStr = Column(String(12), nullable=True)